<?php

namespace ContainerHrjN6Eu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q2DBMJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q2DB_mJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q2DB_mJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agenceRepo' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'code' => ['privates', 'App\\Service\\Code', 'getCodeService', true],
            'compteRepo' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'agenceRepo' => 'App\\Repository\\AgenceRepository',
            'code' => 'App\\Service\\Code',
            'compteRepo' => 'App\\Repository\\CompteRepository',
            'serializer' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
