<?php

namespace ContainerHrjN6Eu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YpgvaaNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YpgvaaN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YpgvaaN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepo' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'code' => ['privates', 'App\\Service\\Code', 'getCodeService', true],
            'compteRepo' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'clientRepo' => 'App\\Repository\\ClientRepository',
            'code' => 'App\\Service\\Code',
            'compteRepo' => 'App\\Repository\\CompteRepository',
            'serializer' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
