<?php

namespace ContainerHrjN6Eu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ATFVPlbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ATFVPlb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ATFVPlb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'frais' => ['privates', 'App\\Service\\Code', 'getCodeService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
        ], [
            'frais' => 'App\\Service\\Code',
            'serializer' => '?',
        ]);
    }
}
